package frc.robot.subsystem.drive;

import edu.wpi.first.math.geometry.Rotation2d;

import frc.robot.subsystem.AbstractSubsystem;

// CTRE Tuner X generated classes
import frc.robot.generated.TunerConstants;
import frc.robot.subsystems.CommandSwerveDrivetrain;

import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.hardware.Pigeon2;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import com.ctre.phoenix6.configs.Pigeon2Configuration;
import com.ctre.phoenix6.configs.MountPoseConfigs;


/**
 * Swerve wrapper with:
 * - True field-centric control using CTRE Phoenix 6
 * - Fixed driver "front" that does not change while driving
 * - No explicit Center-of-Rotation; defaults to robot center
 */
public class SwerveDrivetrain extends AbstractSubsystem {


  // Tunables
  private double maxTranslationalMps = 5.0;
  private double maxRotationalRadPerSec = Math.toRadians(360.0);

  // Driver forward offset (deg). 0 = robot's current physical forward equals field +X (blue side).
  private volatile double driverForwardOffsetDeg = 0.0;

  // CTRE drivetrain generated by Tuner X
  private final CommandSwerveDrivetrain ctre = TunerConstants.createDrivetrain();

  // Cached requests (mutated each loop). We do NOT set CenterOfRotation; default is (0,0).
  private final SwerveRequest.FieldCentric reqField = new SwerveRequest.FieldCentric()
      .withDeadband(0.0)
      .withRotationalDeadband(0.0)
      .withDriveRequestType(DriveRequestType.OpenLoopVoltage);

  private final SwerveRequest.RobotCentric reqRobot = new SwerveRequest.RobotCentric()
      .withDeadband(0.0)
      .withRotationalDeadband(0.0)
      .withDriveRequestType(DriveRequestType.OpenLoopVoltage);

  private final SwerveRequest.PointWheelsAt reqPointForward =
      new SwerveRequest.PointWheelsAt().withModuleDirection(Rotation2d.fromDegrees(0.0));

  public SwerveDrivetrain() {}

  // ---------------------------------------------------------------------------
  // Public API used by Robot.java
  // ---------------------------------------------------------------------------

  /** X=+forward, Y=+left, Omega=+CCW. Field-oriented if foc==true. */
  public void drive(double xForwardCmd, double yLeftCmd, double omegaCCWCmd, boolean foc) {
    final double vx = xForwardCmd * maxTranslationalMps;
    final double vy = yLeftCmd    * maxTranslationalMps;
    final double om = omegaCCWCmd * maxRotationalRadPerSec;

    if (foc) {
      // Field-centric around robot center (default CoR). Do not set withCenterOfRotation.
      ctre.setControl(reqField.withVelocityX(vx).withVelocityY(vy).withRotationalRate(om));
    } else {
      ctre.setControl(reqRobot.withVelocityX(vx).withVelocityY(vy).withRotationalRate(om));
    }
  }

  /** Stop all drive motors. */
  public void stop() {
    ctre.setControl(reqRobot.withVelocityX(0).withVelocityY(0).withRotationalRate(0));
  }
  public void start() { stop(); }

  /** Zero Pigeon yaw. */
  public void zeroGyro() {
    Pigeon2 p2 = ctre.getPigeon2();
    if (p2 != null) p2.setYaw(0.0);
  }

  /** Seed field-centric: current heading becomes 0 from the operator perspective. */
  public void seedFieldCentricNow() { ctre.seedFieldCentric(); }

  /** Set an additional fixed driver-forward offset in degrees. */
  public void setDriverForwardOffsetDegrees(double deg) {
    driverForwardOffsetDeg = deg;
  }

  /** Apply operator perspective forward based on alliance and the fixed offset. */
  public void setOperatorPerspectiveForAlliance() {
    // Blue drivers face +X by default; Red is rotated by 180 degrees.
    boolean isRed = DriverStation.getAlliance().isPresent()
        && DriverStation.getAlliance().get() == Alliance.Red;
    double base = isRed ? 180.0 : 0.0;
    double fwdDeg = base + driverForwardOffsetDeg;
    ctre.setOperatorPerspectiveForward(Rotation2d.fromDegrees(fwdDeg));
  }

  /** Re-apply perspective for the current alliance, then seed field-centric. */
  public void reseedFOCForAlliance() {
    setOperatorPerspectiveForAlliance();
    seedFieldCentricNow();
  }

  /** Point all modules straight ahead (0 deg). */
  public void pointWheelsForward() { ctre.setControl(reqPointForward); }

  public void setDriveMaxAll(double scale) {
    scale = clamp(scale, 0.0, 1.0);
    maxTranslationalMps = 5.0 * scale;
  }
  public void setSteerMaxAll(double scale) {
    scale = clamp(scale, 0.0, 1.0);
    maxRotationalRadPerSec = Math.toRadians(360.0) * scale;
  }
  /** 
 * Invert gyro yaw by toggling mount pose (roll 180 flips yaw sign).
 * Call this once at init, not every loop.
 */
public void setInvertGyroYaw(boolean invert) {
    var p2 = ctre.getPigeon2();
    if (p2 == null) return;
  
    var cfg = new Pigeon2Configuration();
    // Pull current config so we only change what we intend.
    p2.getConfigurator().refresh(cfg);
  
    if (cfg.MountPose == null) cfg.MountPose = new MountPoseConfigs();
    // Keep yaw/pitch as-is; flip roll 0 <-> 180 to invert yaw sign cleanly.
    // If your IMU is physically upside-down, 180 is typically correct.
    cfg.MountPose.MountPoseRoll = invert ? 180.0 : 0.0;
  
    p2.getConfigurator().apply(cfg);
  }

  @Override public void update() { /* CTRE runs its own loops */ }

  private static double clamp(double v, double lo, double hi) {
    return Math.max(lo, Math.min(hi, v));
  }
}
